"""THERE ARE 6 ESCAPE SEQUENCES: 
1) \' : SINGLE QUOTE
2) \" : DOUBLE QUOTE
3) \\ : SINGLE BACKSLASH
4) \n : NEW LINE
5) \t : TAB
6) \b : BACKSPACE

THESE ALL ESCAPE SEQUENCES ARE DISPLAYED IN SPECIFIC FILES WITH EXAMPLES
"""

#EXAMPLES OF ESCAPE SEQUENCES ARE: 
#EXAMPLE 1: 
print("Hello \"World\" world")

#EXAMPLE 2:
print("I\'m Eknoor Singh")